### ISSUE TITLE
CF的xxx.pages.dev支持更换其他前缀

### ISSUE THREAD

**Issue by coppea** [cf-pages/Telegraph-Image#10]
CF给的xxx.pages.dev国内无法访问，是否可以增加前缀域名的设置

返回`/file/90d887c0b455c18.png`后不以当前域名返回`https://xxxx.pages.dev/file/90d887c0b34409c18.png`.而是可以返回自定义设置，如`https://i2.wp.com/telegra.ph/file/90d887c0b8b8eaed09c18.png`

就相当于`https://xxxx.pages.dev/`替换为`https://i2.wp.com/telegra.ph/`，我看修改js就可以，但是混淆了无法修改

**Comment by cf-pages** [comment]
前端代码不是我写的，是直接借用别人（Readme最后有标注）给的代码，故我也不太方便去改动前端（js）的代码

**Comment by coppea** [comment]
自己琢磨修改好了
在文件[b46e75617207ae5013d0.js](https://raw.githubusercontent.com/cf-pages/Telegraph-Image/main/_nuxt/b46e75617207ae5013d0.js)搜索`e.imgUrl=location.origin` 修改为`e.imgUrl="https://i2.wp.com/telegra.ph"`
