### ISSUE TITLE
能正常进Dashboard，但是上传的图片不显示

### ISSUE THREAD

**Issue by CuiXueChao** [cf-pages/Telegraph-Image#102]
![image](https://github.com/cf-pages/Telegraph-Image/assets/34792385/b2c3fa6d-07c2-43ee-a830-8788f4387b98)
上传了好几张图片，但是一直是0

**Comment by LogicalNotZero** [comment]
需要使用上传图片时返回的直链打开一次图片之后，才能在后台查看到。
