### ISSUE TITLE
是不是已经被cf屏蔽了？

### ISSUE THREAD

**Issue by woshichenghaibo** [cf-pages/Telegraph-Image#104]
连接github后提示403错误，您无权查看此页面。
![Screenshot_20240208_082447](https://github.com/cf-pages/Telegraph-Image/assets/80568737/579594d5-aed3-4bf9-a834-792fbf996697)
![Screenshot_20240208_082534](https://github.com/cf-pages/Telegraph-Image/assets/80568737/ae44e43d-ce7e-497b-b743-89f5d553c3ff)
(https://github.com/cf-pages/Telegraph-Image/assets/80568737/9e4fa89d-3c98-418d-a822-cd44b65c8fa2)

**Comment by LogicalNotZero** [comment]
前天刚部署的，也是这个情况。将给CF访问github的授权删除，然后重新授权连接github部署几次。

**Comment by woshichenghaibo** [comment]
> 前天刚部署的，也是这个情况。将给CF访问github的授权删除，然后重新授权连接github部署几次。

重试了好几次，终于成功了
