### ISSUE TITLE
建议在后台给文件添加一个复制链接的按钮

### ISSUE THREAD

**Issue by woshichenghaibo** [cf-pages/Telegraph-Image#116]
进后台后想找找图片链接很麻烦，还得手动复制文件名然后在前面添加不少字符。。。

**Comment by kidwen** [comment]
> 进后台后想找找图片链接很麻烦，还得手动复制文件名然后在前面添加不少字符。。。

已经提了PR，不知道什么时候合并进去, 或者克隆我的仓库先用

**Comment by cf-pages** [comment]
> > 进后台后想找找图片链接很麻烦，还得手动复制文件名然后在前面添加不少字符。。。
> 
> 已经提了PR，不知道什么时候合并进去, 或者克隆我的仓库先用

感谢PR，已经merge了 #115
