### ISSUE TITLE
自定义域名(二级)失败，网页无法访问。

### ISSUE THREAD

**Issue by yachenIiu** [cf-pages/Telegraph-Image#128]
你好，过年那段时间申请的免费的dedyn.io域名，是不支持二级域名还是怎么的？域名托管在了 cf，不知道是我操作有误还是怎么的，希望解答。
![iShot_2024-04-17_17 18 38](https://github.com/cf-pages/Telegraph-Image/assets/154971997/6126ff83-443d-4b36-8207-ccce199a5dc6)

![iShot_2024-04-17_17 23 24](https://github.com/cf-pages/Telegraph-Image/assets/154971997/45427894-2ad2-4fae-94d2-cad5fee2dfdb)

![iShot_2024-04-17_17 24 34](https://github.com/cf-pages/Telegraph-Image/assets/154971997/ee5cab3b-e7e3-4132-8ab0-c1b82ba42530)

![iShot_2024-04-17_17 26 43](https://github.com/cf-pages/Telegraph-Image/assets/154971997/cf8bb042-2386-4f3a-9a89-5e51af00a210)

环境变量和 kv 什么的都设置了，这个跟域名关系不大，总结就是 page 页面功能什么都正常，自定义域名(二级)不正常，是不是还要添加什么解析记录呢？不太懂，比较小白一点，见谅。

**Comment by woshichenghaibo** [comment]
https://github.com/cf-pages/Telegraph-Image/issues/127

看我的反馈，大概率是需要梯子了

**Comment by woshichenghaibo** [comment]
不行，我的是二级域名，tu.gegebu.ru  ，有时候可以访问有时候不行，挂了梯子就一定可以。奇怪了。
________________________________
发件人: BlankSpacezz ***@***.***>
发送时间: 2024年4月17日 22:47
收件人: cf-pages/Telegraph-Image ***@***.***>
抄送: woshichenghaibo ***@***.***>; Comment ***@***.***>
主题: Re: [cf-pages/Telegraph-Image] 自定义域名(二级)失败，网页无法访问。 (Issue #128)


#127<https://github.com/cf-pages/Telegraph-Image/issues/127>

看我的反馈，大概率是需要梯子了

应该不是代理的问题，我平时24小时代理环境的，我看了下自己域名的请求记录显示 DNS error，应该是记录什么没设置对或者配置有问题，你的是二级域名吗？你的是时好时坏还是挂代理域名能进去没问题？

―
