### ISSUE TITLE
有没有picgo的插件

### ISSUE THREAD

**Issue by secflag** [cf-pages/Telegraph-Image#13]
写markdown的时候直接调用picgo上传图片

**Comment by secflag** [comment]
自己改写了一个 有同样需求的可以参考一下：https://github.com/secflag/picgo-plugin-telegraph-image

**Comment by cf-pages** [comment]
感谢分享

**Comment by allinu** [comment]
我使用的是你的这个插件，但是现在遇到了一个问题，图床使用你的readme中的链接可以上传成功，但是使用自己的则是405

<img width="350" alt="image" src="https://user-images.githubusercontent.com/32992109/214330438-95b71274-7f95-45ec-8278-b6b38f26192d.png">

如果有时间还请帮忙看一下 @secflag 

能够上传成功的链接：https://telegraph-image.pages.dev/
不能上传成功的链接：https://telegraph-image-aog.pages.dev/

我的仓库使用的最新的作者代码，我看了一下您的代码，有十次提交没有更新，不知道问题处在哪里，因为最新的代码可以使用后台查看上传记录了，还请您有时间更新一下。🙏

**Comment by frinkleko** [comment]
@allinu 你可以先直接使用这个[插件](https://github.com/yuki-xin/picgo-plugin-web-uploader)如下图进行配置。上面这位作者@secflag 就是在这个插件的基础上改的。我已经在这个插件如下图配置并正常使用。
我和你有一样的情况，我后续会尝试修改@secflag代码并pull requests。
![](https://user-images.githubusercontent.com/32212221/215051701-361e5aae-0a5b-4cd4-848d-ca38e675f6c5.png)

**Comment by allinu** [comment]
@frinkleko 感谢感谢🙏

**Comment by tkmm5201** [comment]
@frinkleko 按照你的配置我使用我搭建的分支显示405错误是不是我什么地方填错了
![image](https://github.com/cf-pages/Telegraph-Image/assets/115028555/22beb0f0-1f0e-4129-8407-8c6f412d64cd)

**Comment by frinkleko** [comment]
> @frinkleko 按照你的配置我使用我搭建的分支显示405错误是不是我什么地方填错了 ![image](https://user-images.githubusercontent.com/115028555/266235150-22beb0f0-1f0e-4129-8407-8c6f412d64cd.png)

我是针对我当时fork的版本做的。我没有关注后续更新的新版本。你可以参考我当时fork的那个Telegraph-Image版本。

**Comment by tkmm5201** [comment]
> > @frinkleko根据您的配置，我使用我的架构的分支显示 405 错误不是我什么地方填错了![图像](https://user-images.githubusercontent.com/115028555/266235150-22beb0f0-1f0e-4129-8407-8c6f412d64cd.png)
> 
> 我是针对我当时fork的版本做的。我没有关注后续更新的新版本。你可以参考我当时fork的那个Telegraph-Image版本。

解决了，其实所有的版本都可以上传的，只是PicGo里面要设置一个代理
![image](https://github.com/cf-pages/Telegraph-Image/assets/115028555/6ebad55d-e9a3-46d8-83c5-086f152117d0)
![image](https://github.com/cf-pages/Telegraph-Image/assets/115028555/eb93ae20-b3b8-46e3-b8c2-4f41c98f1720)
我想有可能是我的网络问题导致的，另外一个大佬的也是可以的粘贴自己的图片网站就可以了。
谢谢大佬的解答@frinkleko

**Comment by dbziye** [comment]
> @allinu 你可以先直接使用这个[插件](https://github.com/yuki-xin/picgo-plugin-web-uploader)如下图进行配置。上面这位作者@secflag 就是在这个插件的基础上改的。我已经在这个插件如下图配置并正常使用。 我和你有一样的情况，我后续会尝试修改@secflag代码并pull requests。 ![](https://user-images.githubusercontent.com/32212221/215051701-361e5aae-0a5b-4cd4-848d-ca38e675f6c5.png)

你好，你的这个插件是你修改了的吗？你这个有自定义url前缀，可不可以分享我一个，谢谢。原生插件配置老是出错。

**Comment by elecDancing** [comment]
@frinkleko 
我的版本无法自定义url每次在typora中还需要加入前缀才能正常显示图片
您的版本是自己修改之后加入了前缀么，可以分享一下么非常感谢

**Comment by FKcrown** [comment]
> @frinkleko 我的版本无法自定义url每次在typora中还需要加入前缀才能正常显示图片 您的版本是自己修改之后加入了前缀么，可以分享一下么非常感谢

在插件商店搜索`custom-uploader`可以搜到

**Comment by elecDancing** [comment]
@FKcrown 非常感谢！！！！！

**Comment by pt-fun** [comment]
现在不能用了
