### ISSUE TITLE
求大佬给个api接口文档，axios报403错误

### ISSUE THREAD

**Issue by ZAIDU-Miren** [cf-pages/Telegraph-Image#134]
使用apifox是正常上传成功的，但是使用axios就报403，看AI解释是CF拦截

**Comment by xyTom** [comment]
如需使用API上传，请自行部署，这边演示站点，每天都会超过cf给的免费额度，所以演示站点开启了cf的bot检测，可能axios被识别成了bot，如果自行部署的话，可到cf后台关闭相关功能就不会被截拦了

**Comment by cf-pages** [comment]
如需使用api接口上传，可以查看：[RapidAPI](https://rapidapi.com/Imgurl/api/imgurl)
