### ISSUE TITLE
下载部署会405

### ISSUE THREAD

**Issue by qinfengge** [cf-pages/Telegraph-Image#14]
但是fork部署它就OK了，我不懂，但我大受震撼

**Comment by mydracula** [comment]
![1677879131350](https://user-images.githubusercontent.com/71320199/222833267-4da44a4a-552d-4e64-a3aa-40a73de6c055.png)

什么原因？

**Comment by dcdebug** [comment]
Same problem ..

**Comment by gogogoghost** [comment]
Same problem

**Comment by gogogoghost** [comment]
![image](https://github.com/cf-pages/Telegraph-Image/assets/29392742/0362f320-265e-43f9-8fbb-061ed951815f)
[Direct Upload](https://developers.cloudflare.com/pages/get-started/direct-upload/) is currently not supported with Functions.

**Comment by SokWith** [comment]
https://github.com/cf-pages/Telegraph-Image/issues/112#issuecomment-2078396390

实在震憾
