### ISSUE TITLE
KV设置正确 进入图片管理页时报错 详细图文描述 跪求大佬解答

### ISSUE THREAD

**Issue by smallcutesheep** [cf-pages/Telegraph-Image#148]
<img width="929" alt="屏幕截图1" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/25481f4d-e3e3-4b80-ab5d-589b43121806">
edge浏览器，进入admin管理页后弹出错误提示

<img width="944" alt="屏幕截图 2024-07-04 191547" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/c1accec9-d9f4-4e6e-b4c3-9c4c19c0318c">
点击“确定”后，出现错误信息

<img width="926" alt="屏幕截图 2024-07-04 191729" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/545c9e7a-8549-432d-9132-c309a167c276">
KV创建正常

![屏幕截图_4-7-2024_19432_dash cloudflare com](https://github.com/cf-pages/Telegraph-Image/assets/118032884/e5f26df6-2e50-4073-8426-c1bb8ff76ab6)
KV变量无数据

![屏幕截图_4-7-2024_194447_dash cloudflare com](https://github.com/cf-pages/Telegraph-Image/assets/118032884/ff9178e0-6143-467c-b0a1-e8131222484a)
控制台函数KV命名空间正常

![屏幕截图_4-7-2024_194544_dash cloudflare com](https://github.com/cf-pages/Telegraph-Image/assets/118032884/cc109093-692c-43b5-bf1a-f0d9d381dd1a)
无任何环境变量
最新设置已部署（上四图）

<img width="938" alt="屏幕截图 2024-07-04 194628" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/056e0f86-c746-4664-af6b-e277c1be95dc">
上传页可以正常访问

<img width="918" alt="屏幕截图 2024-07-04 204758" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/e25f6082-9dab-46ff-804f-3abef1af5b77">
图片上传成功 上传页正常

**Comment by cf-pages** [comment]
后台管理功能需要添加环境变量，具体请查看项目的[README.md](https://github.com/cf-pages/Telegraph-Image#:~:text=2%E3%80%81%E5%90%8E%E5%8F%B0%E7%AE%A1%E7%90%86%E9%A1%B5%E9%9D%A2%E6%96%B0%E5%A2%9E%E7%99%BB%E5%BD%95%E9%AA%8C%E8%AF%81%E5%8A%9F%E8%83%BD%EF%BC%8C%E9%BB%98%E8%AE%A4%E4%B9%9F%E6%98%AF%E5%85%B3%E9%97%AD%E7%9A%84%EF%BC%8C%E5%A6%82%E9%9C%80%E5%BC%80%E5%90%AF%E8%AF%B7%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%90%8E%E5%89%8D%E5%BE%80%E5%90%8E%E5%8F%B0%E4%BE%9D%E6%AC%A1%E7%82%B9%E5%87%BB%E8%AE%BE%E7%BD%AE%2D%3E%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%2D%3E%E4%B8%BA%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E5%AE%9A%E4%B9%89%E5%8F%98%E9%87%8F%2D%3E%E7%BC%96%E8%BE%91%E5%8F%98%E9%87%8F%20%E6%B7%BB%E5%8A%A0%E5%A6%82%E4%B8%8B%E8%A1%A8%E6%A0%BC%E6%89%80%E7%A4%BA%E7%9A%84%E5%8F%98%E9%87%8F%E5%8D%B3%E5%8F%AF%E5%BC%80%E5%90%AF%E7%99%BB%E5%BD%95%E9%AA%8C%E8%AF%81)：
``` 2、后台管理页面新增登录验证功能，默认也是关闭的，如需开启请部署完成后前往后台依次点击设置->环境变量->为生产环境定义变量->编辑变量 添加如下表格所示的变量即可开启登录验证 ```

**Comment by smallcutesheep** [comment]
大佬添加环境变量后还是进不去管理页
![屏幕截图_5-7-2024_16622_dash cloudflare com](https://github.com/cf-pages/Telegraph-Image/assets/118032884/15a41a57-9515-4bbb-8113-03a45e7ab9bc)
其它设置都保持不变 已重新部署 还是一样的提示
<img width="936" alt="屏幕截图 2024-07-05 160934" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/9cfa8017-bdfa-43c8-81ce-8ee7c492f7a5">
<img width="949" alt="屏幕截图 2024-07-05 161104" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/924d534b-9429-4bfd-aa5b-5cf43df49052">
重新部署后上传页依然可以上传图片、生成外链和加载图片
<img width="916" alt="屏幕截图 2024-07-05 161419" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/04a026cd-8df2-4646-8d8f-58f8aad6bc5d">
<img width="955" alt="屏幕截图 2024-07-05 161530" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/f662c7c3-5590-48f4-8976-ba7a6aeef9b2">
再次求大佬解答 @cf-pages

**Comment by cf-pages** [comment]
添加完环境变量后，是否有重新部署？
具体可以参考[README.md](https://github.com/cf-pages/Telegraph-Image#:~:text=%E5%8F%A6%E5%A4%96%E9%92%88%E5%AF%B9%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E6%89%80%E5%81%9A%E7%9A%84%E6%9B%B4%E6%94%B9%E5%B0%86%E5%9C%A8%E4%B8%8B%E6%AC%A1%E9%83%A8%E7%BD%B2%E6%97%B6%E7%94%9F%E6%95%88%EF%BC%8C%E5%A6%82%E6%9B%B4%E6%94%B9%E4%BA%86%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%EF%BC%8C%E9%92%88%E5%AF%B9%E6%9F%90%E9%A1%B9%E5%8A%9F%E8%83%BD%E8%BF%9B%E8%A1%8C%E4%BA%86%E5%BC%80%E5%90%AF%E6%88%96%E5%85%B3%E9%97%AD%EF%BC%8C%E8%AF%B7%E8%AE%B0%E5%BE%97%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2%E3%80%82)：
`另外针对环境变量所做的更改将在下次部署时生效，如更改了环境变量，针对某项功能进行了开启或关闭，请记得重新部署。`

**Comment by cf-pages** [comment]
另外请参考之前其他人提出的 issue #83

**Comment by cf-pages** [comment]
#22 
另外，检查一下环境变量有没有设置正确，注意有下划线，截图当中显示不出来

**Comment by smallcutesheep** [comment]
好的谢谢作者们! 这两天不在家，回去了试试!

**Comment by smallcutesheep** [comment]
谢谢作者们! 这两天不在家，回去了就试试!

**Comment by smallcutesheep** [comment]
好的谢谢作者们! 这两天不在家，回去了就试试!

**Comment by smallcutesheep** [comment]
### 谢谢作者！谢谢朋友们！问题已成功解决！
**我的解决方法就是 issue #83  那封邮件的三张图（issue #83中有）**
<img width="926" alt="屏幕截图 2024-07-08 123458" src="https://github.com/cf-pages/Telegraph-Image/assets/118032884/907681c6-3299-4a89-81e8-f6eaab7f3b89">
三张图片在issue #83 中的定位
也可以直接看我的 #83 截图
![屏幕截图_8-7-2024_12437_github com](https://github.com/cf-pages/Telegraph-Image/assets/118032884/ff20349e-1fea-4e51-ae36-068c4d57eaf9)
**提醒一下，按那三张图片重新部署完成后需要再访问一遍已上传的图片后才能在后台看到你的图片**
感谢作者 @cf-pages  和相同问题的朋友 @rational-stars
第一次在github提问题太激动辣！
另外我建议 @a-w-1806 这位老哥新建一个issue可以被更多人看到
就这么多，closed了~
