### ISSUE TITLE
使用fetch调用上传图片API时，报CORS错误，大家有遇到吗

### ISSUE THREAD

**Issue by xumeng** [cf-pages/Telegraph-Image#165]
上传代码如下，
chrome中看到cors错误，
在safari中看到有一个**OPTIONS**请求，貌似报错。

```
const formData = new FormData();
formData.append('file', file, file.name);

const response = await fetch(
    `${process.env.NEXT_PUBLIC_IMG_URL}/upload`,
    {
        method: 'post',
        body: formData,
    }
);

const result = await response.json();
...
```

使用POSTMAN上传图片是正常的。

**Comment by xumeng** [comment]
我的问题解决了，在nextjs中定义了一个api，再在api里面调用上传接口即可。
希望有帮助。

**Comment by foxhank** [comment]
> 我的问题解决了，在nextjs中定义了一个api，再在api里面调用上传接口即可。 希望有帮助。

佬可以详细说说嘛，我最近研究这个快疯了😭

**Comment by xumeng** [comment]
> > 我的问题解决了，在nextjs中定义了一个api，再在api里面调用上传接口即可。 希望有帮助。
> 
> 佬可以详细说说嘛，我最近研究这个快疯了😭

你的技术栈是什么？我用nextjs。

**❌错误的流程：**
前端页面 -> 上传接口

**✅正确的流程：**
前端页面 -> 新增的nextjs api route -> 上传接口
