### ISSUE TITLE
无法上传图片 2024年9月6日18点28分

### ISSUE THREAD

**Issue by aixindao** [cf-pages/Telegraph-Image#178]
![Snipaste_2024-09-06_18-28-05](https://github.com/user-attachments/assets/48d4f21c-0866-4adb-99df-61554871e23b)

**Comment by yeslinyh** [comment]
me too

**Comment by sucooer** [comment]
可能tg封了

**Comment by mundane799699** [comment]
+1
![Snipaste_2024-09-06_22-04-49](https://github.com/user-attachments/assets/fb63bf7a-a460-48e4-8e3f-ddadd0420bc4)

**Comment by FreeL00P** [comment]
[ "We’ve also disabled new media uploads to Telegraph, our standalone blogging tool, which seems to have been misused by anonymous actors. 
](https://t.me/durov/343)

**Comment by oplxc** [comment]
把接口修一修就可以继续用了。


### 可以自己部署一个兼容程序：

```php
<?php

$targetDir = "file/";
$targetFile = $targetDir . basename($_FILES["file"]["name"]);
$uploadOk = 1;
$imageFileType = strtolower(pathinfo($targetFile, PATHINFO_EXTENSION));

if (isset($_POST["submit"])) {
    $check = getimagesize($_FILES["file"]["tmp_name"]);
    if ($check !== false) {
        //echo "Log: File-mine" . $check["mime"] . ".";
        $uploadOk = 1;
    } else {
        //echo "Log: mine err";
        $uploadOk = 0;
    }
}

if (file_exists($targetFile)) {
    //echo "Log: file exists.";
    $uploadOk = 0;
}

if ($_FILES["file"]["size"] > 5000000) { // 限制为5M
    //echo "Log: file too big.";
    $uploadOk = 0;
}

if (!in_array($imageFileType, ["jpg", "png", "jpeg", "gif"])) {
    echo "Log:Only upload: JPG, JPEG, PNG & GIF file.";
    $uploadOk = 0;
}

if ($uploadOk == 0) {
    echo '{"msg":"upload fail."}';
} else {
    if (move_uploaded_file($_FILES["file"]["tmp_name"], $targetFile)) {
        $responsex = [["src" => $targetFile]];
        echo json_encode($responsex);
    } else {
        echo '{"msg":"500 ERROR."}';
    }
}
?>
```

把上面程序任意丢在php运行环境中，配置好伪静态 **/upload - > /upload.php**，配置好同目录文件夹 `./file/`。就能用了，

要自用的话，可以配合IP白名单+反代鉴权。

程序自测，有bug自修。改接口地址就能用了

**Comment by ifanrvpn** [comment]
me too ,  大佬们代替方案还是啥？

**Comment by ifanrvpn** [comment]
> 把接口修一修就可以继续用了。
> 
> ### 可以自己部署一个兼容程序：
> ```
> <?php
> 
> $targetDir = "file/";
> $targetFile = $targetDir . basename($_FILES["file"]["name"]);
> $uploadOk = 1;
> $imageFileType = strtolower(pathinfo($targetFile, PATHINFO_EXTENSION));
> 
> if (isset($_POST["submit"])) {
>     $check = getimagesize($_FILES["file"]["tmp_name"]);
>     if ($check !== false) {
>         //echo "Log: File-mine" . $check["mime"] . ".";
>         $uploadOk = 1;
>     } else {
>         //echo "Log: mine err";
>         $uploadOk = 0;
>     }
> }
> 
> if (file_exists($targetFile)) {
>     //echo "Log: file exists.";
>     $uploadOk = 0;
> }
> 
> if ($_FILES["file"]["size"] > 5000000) { // 限制为5M
>     //echo "Log: file too big.";
>     $uploadOk = 0;
> }
> 
> if (!in_array($imageFileType, ["jpg", "png", "jpeg", "gif"])) {
>     echo "Log:Only upload: JPG, JPEG, PNG & GIF file.";
>     $uploadOk = 0;
> }
> 
> if ($uploadOk == 0) {
>     echo '{"msg":"upload fail."}';
> } else {
>     if (move_uploaded_file($_FILES["file"]["tmp_name"], $targetFile)) {
>         $responsex = [["src" => $targetFile]];
>         echo json_encode($responsex);
>     } else {
>         echo '{"msg":"500 ERROR."}';
>     }
> }
> ?>
> ```
> 
> 把上面程序任意丢在php运行环境中，配置好伪静态 **/upload - > /upload.php**，配置好同目录文件夹 `./file/`。就能用了，
> 
> 要自用的话，可以配合IP白名单+反代鉴权。
> 
> 程序自测，有bug自修。改接口地址就能用了

我的天  我菜鸟看不明白

**Comment by buganmao** [comment]
+1

**Comment by cf-pages** [comment]
请查看issue：#180 
Telegram官方取消了上传接口，目前正在寻找替代的上传方案

**Comment by woshichenghaibo** [comment]
> 把接口修一修就可以继续用了。
> 
> ### 可以自己部署一个兼容程序：
> ```
> <?php
> 
> $targetDir = "file/";
> $targetFile = $targetDir . basename($_FILES["file"]["name"]);
> $uploadOk = 1;
> $imageFileType = strtolower(pathinfo($targetFile, PATHINFO_EXTENSION));
> 
> if (isset($_FILES['file'])) {
>     $check = getimagesize($_FILES["file"]["tmp_name"]);
>     if ($check !== false) {
>         //echo "Log: File-mine" . $check["mime"] . ".";
>         $uploadOk = 1;
>     } else {
>         //echo "Log: mine err";
>         $uploadOk = 0;
>     }
> }
> 
> if (file_exists($targetFile)) {
>     //echo "Log: file exists.";
>     $uploadOk = 0;
> }
> 
> if ($_FILES["file"]["size"] > 5000000) { // 限制为5M
>     //echo "Log: file too big.";
>     $uploadOk = 0;
> }
> 
> if (!in_array($imageFileType, ["jpg", "png", "jpeg", "gif"])) {
>     echo "Log:Only upload: JPG, JPEG, PNG & GIF file.";
>     $uploadOk = 0;
> }
> 
> if ($uploadOk == 0) {
>     echo '{"msg":"upload fail."}';
> } else {
>     if (move_uploaded_file($_FILES["file"]["tmp_name"], $targetFile)) {
>         $responsex = [["src" => $targetFile]];
>         echo json_encode($responsex);
>     } else {
>         echo '{"msg":"500 ERROR."}';
>     }
> }
> ?>
> ```
> 
> 把上面程序任意丢在php运行环境中，配置好伪静态 **/upload - > /upload.php**，配置好同目录文件夹 `./file/`。就能用了，
> 
> 要自用的话，可以配合IP白名单+反代鉴权。
> 
> 程序自测，有bug自修。改接口地址就能用了

就这么简单？

**Comment by oplxc** [comment]
> How to deploy a compatible program of your own? Are there any reference examples? Do I still need to buy a server?

Any PHP environment can be deployed, including free php host, virtual php host, vps, etc.

**Comment by ohn-max** [comment]
B站搜索“Telegraph图床（Unknown Error）完美兼容老版本”有解决视频

**Comment by woshichenghaibo** [comment]
> B站搜索“Telegraph图床（Unknown Error）完美兼容老版本”有解决视频

确实不错，我试试

**Comment by kenchikuliu** [comment]
![图片](https://github.com/user-attachments/assets/bd1613d4-0741-4ff1-87d0-4e7ddc2f5ab0)

**Comment by cf-pages** [comment]
匿名上传接口目前已经失效，目前项目最新代码是使用tg bot的方式上传，如有需要可以重新部署最新的代码
