### ISSUE TITLE
Dashboard is disabled. Please bind a KV namespace to use this feature.

### ISSUE THREAD

**Issue by LONELYLI666** [cf-pages/Telegraph-Image#18]
部署完访问地址/admin报错
![IMG_20230118_184920](https://user-images.githubusercontent.com/78999498/213152545-fd72b2c5-9582-462d-883d-69fb0291df12.jpg)
![IMG_20230118_184845](https://user-images.githubusercontent.com/78999498/213152569-34967c94-4dff-4364-8dfc-20796e27ebe4.jpg)

**Comment by cf-pages** [comment]
更新了新版本的代码，请重新部署试下

如何部署最新版本？
可参考，已经部署了的，如何更新？https://github.com/cf-pages/Telegraph-Image/issues/14

**Comment by coppea** [comment]
变量名称是  `img_url`，不是`img url`

**Comment by LONELYLI666** [comment]
解决了
