### ISSUE TITLE
Telegram不再支持向Telegraph上传媒体文件，以后不能用了

### ISSUE THREAD

**Issue by 5mdld** [cf-pages/Telegraph-Image#180]
消息链接：https://t.me/durov/343

> ✂️ We’ve also disabled new media uploads to Telegraph, our standalone blogging tool, which seems to have been misused by anonymous actors. 

_✂️ 我们还禁用了独立博客工具Telegraph的新媒体上传功能，因为它似乎被匿名用户滥用了。_

以后不能用了，大家不用提issue了

**Comment by Axoloteera** [comment]
恐怖.难怪我今天上传总是出现"Unknown Error".

**Comment by cf-pages** [comment]
感谢反馈！已将信息添加到项目的Readme当中，貌似目前已经上传的图片仍然可以正常加载，我们也正在寻找替代方案。

**Comment by chai3721** [comment]
什么被匿名用户滥用了？本来就不用登录就能上传的呀，不存在被匿名用户滥用了。再说上传读取都有次数限制的。

**Comment by woshichenghaibo** [comment]
没懂，这两个是同一家公司的？

**Comment by ilyton** [comment]
I just said why the upload keeps failing

**Comment by ohn-max** [comment]
B站搜索“Telegraph图床（Unknown Error）完美兼容老版本”有解决视频
