### ISSUE TITLE
tg频道作为存储？

### ISSUE THREAD

**Issue by wunskzb** [cf-pages/Telegraph-Image#182]
能否搞个tg频道或群组作为存储后端来做图床？

**Comment by b996558** [comment]
有这个项目实现这个功能。具体见https://github.com/x-dr/telegraph-Image

**Comment by MarSeventh** [comment]
也可以看看我的，已经迁移至tg频道上传，https://github.com/MarSeventh/CloudFlare-ImgBed

**Comment by cf-pages** [comment]
请查看telegram-bot-api 分支：https://github.com/cf-pages/Telegraph-Image/tree/feature/telegram-bot-api
