### ISSUE TITLE
绑定自定义域名之后，使用自定义域名上传的图片，后台无法被记录,kv也无记录

### ISSUE THREAD

**Issue by coppea** [cf-pages/Telegraph-Image#19]
不光自定义域名，自带域名 xxx.pages.dev ，后台也无法记录

**Comment by cf-pages** [comment]
修改环境变量或是添加绑定后请尝试重新部署一下
![](https://camo.githubusercontent.com/ae297494d145fd8fd61106b98cccde071546b626c4bbc24bbfff73fbdf2f9d8b/68747470733a2f2f696d2e6775726c2e65752e6f72672f66696c652f6235313434363761346233626530353637613736662e706e67)

**Comment by coppea** [comment]
这些已经操作过了，还是不行，后台就是没有照片记录
<img width="882" alt="iShot_2023-01-19_13 17 00" src="https://user-images.githubusercontent.com/86509331/213361428-532c24c0-38a9-4232-b425-200c09d0ae8c.png">
<img width="1110" alt="iShot_2023-01-19_13 17 43" src="https://user-images.githubusercontent.com/86509331/213361435-9f51a422-01ea-4b51-8131-a7b1db1af77f.png">

**Comment by coppea** [comment]
图片上传后，kv就没有写入任何数据

**Comment by cf-pages** [comment]
删除该pages项目，创建一个新的项目，完全重新部署试试？

**Comment by coppea** [comment]
重新fork还是不行
我等等大家的反馈，不可能只有我一个人遇到

**Comment by zoer98** [comment]
我也遇到了，不然是自定义域名还是默认域名，上传后管理页面都没有记录

**Comment by cf-pages** [comment]
我这边尝试重新创建了一个github账号，fork本项目，去cloudflare pages里面部署本项目，一切正常，没能成功复现问题，我把我的环境变量截图贴出来共大家参考比较一下，看下问题出在哪里

![](https://im.gurl.eu.org/file/8340a3f0d2be7ff935389.png)
![](https://im.gurl.eu.org/file/f4c731fced01ef0628fb1.png)

**Comment by cf-pages** [comment]
> 不光自定义域名，自带域名 xxx.pages.dev ，后台也无法记录

我这边看到你的https://cec7eb75.tg-3hl.pages.dev/后台记录是正常的

**Comment by coppea** [comment]
我发现奇怪逻辑
上传完照片成功后，查看xxx.com/admin后台无记录，在cloudflare的kv查看也没有数据
如果点击上传完的图片https://xxx.abc.com/file/c8287411e4b3a665c302c.jpg,再查看kv就有数据了

这个实在不懂，你可以用这个域名试试https://tg-3hl.pages.dev/

**Comment by cf-pages** [comment]
> 我发现奇怪逻辑 上传完照片成功后，查看xxx.com/admin后台无记录，在cloudflare的kv查看也没有数据 如果点击上传完的图片[https://xxx.abc.com/file/c8287411e4b3a665c302c.jpg,再查看kv就有数据了](https://xxx.abc.com/file/c8287411e4b3a665c302c.jpg,%E5%86%8D%E6%9F%A5%E7%9C%8Bkv%E5%B0%B1%E6%9C%89%E6%95%B0%E6%8D%AE%E4%BA%86)
> 
> 这个实在不懂，你可以用这个域名试试，看看能不能复现https://tg-3hl.pages.dev/

好吧，搞了半天原来是这个原因 🤦‍ 这个是特性，图片上传后不会立刻在后台显示出来，而是需要通过你的域名加载过该张图片才会记录下来，该设计该机制的原因是：

1、由于之前版本的程序没有后台图片管理记录功能，如果需要图片上传之后才记录的话，则无法追溯之前没有该功能前就上传了的图片，而通过加载图片记录，则只要之前的图片被加载则可以记录上之前上传的图片，可以看作是一种兼容以前的图片

2、程序所依赖的后端图片储存空间是telegraph，telegraph有官方的API接口可以上传图片，即图片不一定需要通过你部署的域名上传，故为了统计通过其他方式上传，但通过你的域名加载的图片，采取了这种方式。这样就能统计到不通过你域名上传，但通过你域名加载的图片

这一机制在readme中有提到，但可能写的不是很明显，造成了困扰：
>10、新增后台图片预览功能 当开启图片管理功能后，可在后台预览**通过你的域名加载过**的图片

**Comment by cf-pages** [comment]
> 我也遇到了，不然是自定义域名还是默认域名，上传后管理页面都没有记录

图片上传后不会立刻在后台显示出来，而是需要通过你的域名加载过该张图片才会记录下来，你可以试试上传图片后先手动访问一次图片，看看后台是否会有记录

**Comment by coppea** [comment]
哈哈，谢谢解答

**Comment by coppea** [comment]
我用的是第三方代理域名来加速，如`https://i0.wp.com/telegra.ph/file/d64d83d0a98190cdb658c.png`

这样就没发通过域名加载过图片才能再后台显示，我觉得可以优化逻辑，之后上传的图片不需要域名加载过，可以直接在后台显示。之前上传过的图片通过域名加载过该图片还可以继续记录下来

不知道这样是否复杂

**Comment by zhecydn** [comment]
我也遇到了这个问题，需要先加载一遍部署过的图片才可以在后台显示出来，所以请问一下怎么解决

**Comment by 6uu1** [comment]
> 我用的是第三方代理域名来加速，如`https://i0.wp.com/telegra.ph/file/d64d83d0a98190cdb658c.png`
> 
> 这样就没发通过域名加载过图片才能再后台显示，我觉得可以优化逻辑，之后上传的图片不需要域名加载过，可以直接在后台显示。之前上传过的图片通过域名加载过该图片还可以继续记录下来
> 
> 不知道这样是否复杂

可以请教一下，这个https://i0.wp.com/是怎么实现代理的吗?

**Comment by gitcomy** [comment]
不知道为什么，自定义域名一直显示停用/错误，cname设置了三天了。
https://telegraph-image-ddn.pages.dev/file/f31babb21bced40288a1a.png
https://telegraph-image-ddn.pages.dev/file/74bb5ed7787526745115c.png

**Comment by yzxicq** [comment]
@cf-pages 这条issue 你准备修么？

**Comment by woshichenghaibo** [comment]
> > 我发现奇怪逻辑 上传完照片成功后，查看xxx.com/admin后台无记录，在cloudflare的kv查看也没有数据 如果点击上传完的图片[https://xxx.abc.com/file/c8287411e4b3a665c302c.jpg,再查看kv就有数据了](https://xxx.abc.com/file/c8287411e4b3a665c302c.jpg,%E5%86%8D%E6%9F%A5%E7%9C%8Bkv%E5%B0%B1%E6%9C%89%E6%95%B0%E6%8D%AE%E4%BA%86)
> > 这个实在不懂，你可以用这个域名试试，看看能不能复现https://tg-3hl.pages.dev/
> 
> 好吧，搞了半天原来是这个原因 🤦‍ 这个是特性，图片上传后不会立刻在后台显示出来，而是需要通过你的域名加载过该张图片才会记录下来，该设计该机制的原因是，为了能够记录到尽可能多的图片，具体来说：
> 
> 1、由于之前版本的程序没有后台图片管理记录功能，如果需要图片上传之后才记录的话，则无法追溯之前没有该功能前就上传了的图片，而通过加载图片记录，则只要之前的图片被加载则可以记录上之前上传的图片，可以看作是一种兼容以前的图片
> 
> 2、程序所依赖的后端图片储存空间是telegraph，telegraph有官方的API接口可以上传图片，即图片不一定需要通过你部署的域名上传，故为了统计通过其他方式上传，但通过你的域名加载的图片，采取了这种方式。这样就能统计到不通过你域名上传，但通过你域名加载的图片
> 
> 这一机制在readme中有提到，但可能写的不是很明显，造成了困扰：
> 
> > 10、新增后台图片预览功能 当开启图片管理功能后，可在后台预览**通过你的域名加载过**的图片

你看能不能这个在上图片上传完成之后，在页面自动访问一下，这张图片算是首次访问
