### ISSUE TITLE
上传的图片全部变成404了

### ISSUE THREAD

**Issue by nihaohellohola** [cf-pages/Telegraph-Image#192]
![Screenshot 2024-09-30 215256](https://github.com/user-attachments/assets/c86ee9b9-89e8-4fa6-bd35-0b94f6949155)

**Comment by Komorebi-yaodong** [comment]
我也遇到了该问题

**Comment by asdfghkl12345** [comment]
我也遇到了问题，上传后的图片，一天后就404 not found，无法访问了。让我只能先用其他图床先代替。

**Comment by mc-sep** [comment]
我也是这样

受害者：https://blog.mc-sep.top/post/5trr.html
