### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by yanyu03** [cf-pages/Telegraph-Image#204]
**如图所示**
fork之后部署的
<img width="231" alt="{E7FEC6C6-C68A-41D7-9336-0863C77E4AC9}" src="https://github.com/user-attachments/assets/26907490-890a-45d0-affe-c7ba56c284fa">

**Comment by 362190147** [comment]
不知道你什么原因，但是你弄好以后一天不到就失效了。别浪费时间

**Comment by yanyu03** [comment]
我是fork以后拿去按步走，部署完了也用不了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 362190147** [comment]
说了弄好了也没用。弄好以后图片很快失效。原因你看前面的 issue

**Comment by yanyu03** [comment]
我是后面才知道项目没了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cf-pages** [comment]
项目原来使用的上传接口目前已经失效，目前项目最新代码是使用tg bot的方式上传，如有需要可以重新部署最新的代码
