### ISSUE TITLE
配置环境变量重新部署后仍然无法上传，见下图

### ISSUE THREAD

**Issue by LegendarySSS** [cf-pages/Telegraph-Image#209]
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/a5b2c29b-ce17-47ea-aa8c-df9ac069817a">
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/3a6cd5e8-5b6b-4f69-a30a-a5195895a497">

**Comment by LegendarySSS** [comment]
缓存问题，已解决

**Comment by aric6494** [comment]
> 缓存问题，已解决

我遇到的是和你一样的问题，请问是怎么解决的。
