### ISSUE TITLE
上传图床后图片地址在新标签打开都会直接下载图片而不是在新标签查看图片，能否做到查看图片？

### ISSUE THREAD

**Issue by kitia01** [cf-pages/Telegraph-Image#213]
测试下新标签图片返回的是 application/octet-stream 类型，并且设置了 Content-Disposition: attachment作为附件下载，而不是作为可视化图片在浏览器中打开。

**Comment by kitia01** [comment]
目前定位原因大概是因为用的电报的bot导致响应头只有二进制，我研究了个暂时的方法，使用cf的worker以及路由，动态解析图片url的后缀名修改cors。步骤1：创建新的cf的worker，部署代码`addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  const url = new URL(request.url)
  const fileExtension = url.pathname.split('.').pop().toLowerCase()

  // 获取原始响应
  const response = await fetch(request)

  // 创建新的响应，保留原始 Content-Type
  const modifiedResponse = new Response(response.body, response)

  // 根据文件扩展名设置 Content-Type（如果是已知图像类型）
  let contentType = response.headers.get('Content-Type')
  if (fileExtension === 'jpg' || fileExtension === 'jpeg') {
      contentType = 'image/jpeg'
  } else if (fileExtension === 'png') {
      contentType = 'image/png'
  } else if (fileExtension === 'webp') {
      contentType = 'image/webp'
  }

  // 修改 Content-Type 和 Content-Disposition
  modifiedResponse.headers.set('Content-Type', contentType)
  modifiedResponse.headers.set('Content-Disposition', 'inline')

  return modifiedResponse
}
`
然后用worker路由去代理图床的url，在无痕模式下排除磁盘缓存进行尝试，结果是ok的。

**Comment by Jaredxh** [comment]
厉害厉害，具体步骤如何操作呢？原项目不要了，从这个新项目里配置Git啥的吗

**Comment by kitia01** [comment]
> 厉害厉害，具体步骤如何操作呢？原项目不要了，从这个新项目里配置Git啥的吗

你可以参考这个仓库的https://github.com/kitia01/telegraph-image-contentType-proxy 进行操作

**Comment by Jaredxh** [comment]
我看了，但是我那个新workers项目的路由不会配置，需要添加域，但是有没有显示老项目的子域选项，自己填也无法识别

**Comment by Jaredxh** [comment]
![image](https://github.com/user-attachments/assets/733b06da-2dd9-4c85-b203-4086fccfd9bd)

**Comment by Jaredxh** [comment]
![image](https://github.com/user-attachments/assets/74022b9d-e00d-4f2a-8986-9417c03d2afc)

**Comment by Jaredxh** [comment]
我理解你的处理方法是，新建一个workers项目编辑你写的代码，然后配置路由指向老得Workers图床项目，来处理图片预览问题，是这样吗

**Comment by kitia01** [comment]
是的，但如果你想使用cloudflare的路由你就必须拥有一个自己的域名，并且把这个域名托管到cloudflare上才行，你可以去B站搜下cloudflare相关的内容去了解下，你这个pages.dev是cloudflare自己的域名，是不能进行dns托管的

**Comment by Jaredxh** [comment]
明白了，cf得子域名没法用

**Comment by Jaredxh** [comment]
我这里已经配置好了路由，但还是没有实现在线预览，请问还有什么修改的地方我没处理好吗
![image](https://github.com/user-attachments/assets/8936225a-7a09-4177-b09f-41a445cfc1dd)
