### ISSUE TITLE
设置验证登录环境变量后后台管理界面无登录验证

### ISSUE THREAD

**Issue by a2603802339** [cf-pages/Telegraph-Image#34]
![image](https://user-images.githubusercontent.com/54015894/219868386-ed749c55-b3ae-471b-9ca7-62f59693ad1e.png)

**Comment by cf-pages** [comment]
设置完环境变量后，需要`重新部署`才能生效

**Comment by a2603802339** [comment]
> 设置完环境变量后，需要`重新部署`才能生效

重新部署试了好几次了还是没有
