### ISSUE TITLE
希望增加API上传图片功能/私有图床功能

### ISSUE THREAD

**Issue by Nx-117** [cf-pages/Telegraph-Image#35]
希望增加API上传图片功能  还有 就是自己私有的图床功能，虽说是部署到公网上但是还希望只能自己上传 因为我打算开商业版本 怕被刷量= =

**Comment by Christ9038** [comment]
前端也是调用upload方法上传，CloudFlare Access给upload设置权限就可以了。其他人只能访问到首页，但是没验证前，是无法上传成功的。

**Comment by Nx-117** [comment]
好的感谢
