### ISSUE TITLE
视频的大小限制是多少？

### ISSUE THREAD

**Issue by lancer-wang** [cf-pages/Telegraph-Image#37]
我试着传了个30m的视频，然后提示
413 Request Entity Too Large
![image](https://user-images.githubusercontent.com/69783837/228414131-4c76298b-217a-4121-afab-bd7d48b007cf.png)

视频的大小限制是多少

**Comment by cf-pages** [comment]
和图像的大小限制一样，都是10M

**Comment by lancer-wang** [comment]
> 和图像的大小限制一样，都是10M

好的
