### ISSUE TITLE
上传的视频无法在管理里面看到

### ISSUE THREAD

**Issue by xfxx2022** [cf-pages/Telegraph-Image#38]
已经访问过视频，可以打开，但是管理里面还是没有

**Comment by cf-pages** [comment]
感谢反馈，因为管理页面设计时候未考虑到上传视频的情况，开发管理页面时还没有支持视频上传，后续会计划修复此问题

**Comment by RavenHuo** [comment]
上传的图片，ulr要访问一下才能在管理界面中显示
这个应该是一个bug

**Comment by yukikaze1234** [comment]
> 上传图片，ulr要访问一下才能在管理界面中显示 这应该是一个bug

楼主说的对，是bug。

**Comment by Paxton0222** [comment]
> > 上传图片，ulr要访问一下才能在管理界面中显示 这应该是一个bug
> 
> 楼主说的对，是bug。

same issue here

**Comment by cf-pages** [comment]
#63
