### ISSUE TITLE
已经设置好了KV空间，但是进入管理页面依旧提示被禁用

### ISSUE THREAD

**Issue by flyhunterl** [cf-pages/Telegraph-Image#47]
An error occurred while synchronizing data with the server, please check the network connection
弹个窗口提示这个后
提示Dashboard is disabled. Please bind a KV namespace to use this feature.

![图片](https://tk.jdonkey.club/file/01224a4506c010f8dbfc8.png)

**Comment by zip8919** [comment]
我也是
