### ISSUE TITLE
图片访问跨域

### ISSUE THREAD

**Issue by Nothingtodoforma** [cf-pages/Telegraph-Image#53]
如题，为什么我上传图片后调用会有跨域问题啊

**Comment by Nothingtodoforma** [comment]
_解决方法如下（仅针对自定义域名）：_
**1.在cloudflare的域名菜单中找到转换规则子菜单**
![image](https://github.com/cf-pages/Telegraph-Image/assets/49300630/37630cb4-9117-4645-a8e0-1b6c6a884116)
**2.选择修改响应头**
![image](https://github.com/cf-pages/Telegraph-Image/assets/49300630/217bcec9-4370-4991-8761-75e578b485b6)
**3.修改相关响应标头即可**
![image](https://github.com/cf-pages/Telegraph-Image/assets/49300630/e2f030c9-269c-4ee4-8d11-b4b2faf3b922)

**Comment by Nothingtodoforma** [comment]
.

**Comment by xumeng** [comment]
#165 大佬 这个错误有遇到过吗，域名不是CF的，在阿里云上购买的。
