### ISSUE TITLE
出错啦，请重新上传

### ISSUE THREAD

**Issue by standee2023** [cf-pages/Telegraph-Image#59]
部署好后，一上传就提示“出错啦，请重新上传”，用官方的演示站点也一样

**Comment by cf-pages** [comment]
由于目前后端图片储存依赖的是Telegraph的服务器，该服务有时候会不稳定，导致无法上传图片，一般过一会后再次尝试上传就好，如果还是有问题可以尝试重新部署一下

**Comment by standee2023** [comment]
有大佬最近二天上传成功的吗？
