### ISSUE TITLE
如何彻底的删除上传的图片

### ISSUE THREAD

**Issue by S1U** [cf-pages/Telegraph-Image#62]
1. 上传了，但没有加载过的图片，怎么删除？
2. 加载过的图片，在后台里删除，是真正的删除了吗，还是删除的是链接，图片依旧在Telegrah的服务器上？
3. 删除了部署的项目pages，图片随之删除吗？
4. 第一次部署了项目，添加了自定义域名，后来删除了这个部署的项目，但是没有在后台里点“删除”图片。随后又新建了个，添加了同一个自定义域名。发现访问第一次部署项目上传的图片还在，依旧在后台里。为什么？是不是意味着第3点，删除项目并没有删除项目里的图片？

**Comment by Nine499** [comment]
图片依旧在Telegrah的服务器上

**Comment by S1U** [comment]
所以没法实现真正的“删除”是吗？

**Comment by cf-pages** [comment]
> 所以没法实现真正的“删除”是吗？

是的，因为图片是存在Telegraph的服务器上，Telegraph目前还未提供删除图片的接口
