### ISSUE TITLE
删除后刷新页面 删除的数据从新出现

### ISSUE THREAD

**Issue by hzb888** [cf-pages/Telegraph-Image#64]
删除后刷新页面 删除的数据从新出现
后台管理页面。   具体出发逻辑好像是 我又访问了链接 管理后台又有了 图片 删掉后刷新。又重新出现

**Comment by HP-seven** [comment]
作者已经说了：新增记录删除功能 当开启图片管理功能后，可在后台手动删除图片记录，即不再后台显示该图片，除非有人再次上传并加载该图片，注意由于图片储存在telegraph的服务器上，我们无法删除上传的原始图片，只能通过上述第6点的黑名单功能屏蔽图片的加载
