### ISSUE TITLE
设置环境变量之后访问admin面板账号密码

### ISSUE THREAD

**Issue by chsenc** [cf-pages/Telegraph-Image#68]
之前的是第一版，更新后账号密码验证不生效。删除fork和pages，重新fork并创建pages，添加环境变量并重新部署，访问管理面板还是不验证账号密码，请问问题出在哪里？

**Comment by cf-pages** [comment]
https://github.com/cf-pages/Telegraph-Image/issues/22
检查一下环境变量有没有设置正确，注意有下划线，截图当中显示不出来

**Comment by chsenc** [comment]
我环境变量都是从git复制的，不是手填的。

**Comment by chsenc** [comment]
https://imgu.pages.dev/file/86006f4e785cbf9584e13.png

**Comment by chsenc** [comment]
https://imgu.pages.dev/file/30773f44bd81f6586e688.png

**Comment by cf-pages** [comment]
![image](https://github.com/cf-pages/Telegraph-Image/assets/80505777/056a00ea-3d05-420a-adfb-cac13007a75c)
环境变量名称不需要加=号

**Comment by chsenc** [comment]
之前用的时候环境变量没加=号，上午重新部署之后才加的，现在可以了，应该是fork项目的问题，猜测应该是fork项目的时候默认勾选的那个只fork main的原因。
