### ISSUE TITLE
求助大佬， 图片命名可以不变么？可以通过文件夹整个上传么？

### ISSUE THREAD

**Issue by Grand2018** [cf-pages/Telegraph-Image#75]
求助 大佬，图片命名可以不变么？可以通过文件夹整个上传么？
例如 001.jpg   域名.dev/001.jpg

**Comment by cf-pages** [comment]
目前暂时不可以，由于tg那边的限制，上传的图片文件名会被自动重命名，需要自行记录新的图片文件名称和原来图片文件名之间的对应关系
