### ISSUE TITLE
部署之后无法上传图片

### ISSUE THREAD

**Issue by hyy34** [cf-pages/Telegraph-Image#79]
下载zip，解压文件夹，文件夹更名为Telegraph-Image，上传文件夹，可以打开主页，但是上传图片时，出现
![wSqIzZGLXF](https://github.com/cf-pages/Telegraph-Image/assets/26433019/09037853-fee7-4493-8e70-11582c0ddce9)
请问是什么步骤可能出现问题呢？

**Comment by Z1011295099** [comment]
下载部署的405，作者暂时没有解决，fork部署可以。

**Comment by gogogoghost** [comment]
See https://github.com/cf-pages/Telegraph-Image/issues/14#issuecomment-1978085558. Issue could be closed.
