### ISSUE TITLE
upic中应该怎么配置呢，有人配置成功了吗

### ISSUE THREAD

**Issue by handbye** [cf-pages/Telegraph-Image#80]
我按照下面这样配置，获取到的图片路径是null
![image](https://github.com/cf-pages/Telegraph-Image/assets/26617058/3a92f9e2-933b-4691-bc07-07bc61cd2e2d)

**Comment by kamasylvia** [comment]
同样的问题，请问你设置成功了吗

**Comment by handbye** [comment]
> 同样的问题，请问你设置成功了吗

添加个header字段就行了
![image](https://github.com/user-attachments/assets/2b97cce8-0bf1-48de-94a2-2b9c77090877)

**Comment by kamasylvia** [comment]
感谢，成功了
