### ISSUE TITLE
我设置了 kv 变量  还是进入不到后台管理页面

### ISSUE THREAD

**Issue by rational-stars** [cf-pages/Telegraph-Image#83]
<img width="1742" alt="image" src="https://github.com/cf-pages/Telegraph-Image/assets/65513250/f6513576-d474-4ef4-a10d-6ec059897263">

**Comment by rational-stars** [comment]
重新部署 还是一样  求解  也手动访问了 上传的图片地址

**Comment by pxhzai** [comment]
结合我回复你的2张图修改。

**Comment by fluway** [comment]
老哥我也遇到了同样的问题，能说说是怎么解决的么？（我看另一位老哥给你发了三张图片，能共享么）

**Comment by rational-stars** [comment]
@fluway 
![image](https://github.com/cf-pages/Telegraph-Image/assets/65513250/1c2166ce-af3a-4255-915b-7a9ce917a85c)
![image](https://github.com/cf-pages/Telegraph-Image/assets/65513250/3935171b-5e56-472e-b2c0-40104b4d8298)
![image](https://github.com/cf-pages/Telegraph-Image/assets/65513250/72ff6aca-883b-4d05-b63e-fe646115d642)
这是那三张图片
<img width="2921" alt="image" src="https://github.com/cf-pages/Telegraph-Image/assets/65513250/b95581bc-cfc4-4a67-b19f-5917bf897778">
这是我的解决方法

**Comment by zhanziyang** [comment]
对，要重新部署

**Comment by rational-stars** [comment]
1
